# Generated by Django 4.2.4 on 2023-08-20 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0005_auto_20201215_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
    ]
